return {
  -- "sindrets/diffview.nvim",
  -- event = "VeryLazy",
  -- enabled = false, -- now i use codediff.nvim
  -- opts = {
  --   file_panel = {
  --     win_config = {
  --       position = "bottom",
  --       height = 10,
  --     },
  --   },
  --   file_history_panel = {
  --     win_config = {
  --       height = 10,
  --     },
  --   },
  -- },
  --
  -- keys = {
  --   { "<leader>gd", ":DiffviewOpen<CR>", silent = true, desc = "Open Diffview" },
  --   { "<leader>gf", ":DiffviewFileHistory %<CR>", silent = true, desc = "File History" },
  --   { "<leader>gq", ":DiffviewClose<CR>", silent = true, desc = "Close Diffview" },
  --   {
  --     "<leader>gD",
  --     function()
  --       vim.fn.feedkeys(":DiffviewOpen ", "n")
  --     end,
  --     desc = "DiffviewOpen Motion",
  --   },
  -- },
}
